### Unemployment Rate 2021-2024

In [ ]:
# Unemployment Rate (city-level)
import pandas as pd

df_work1 = pd.read_csv("../data/raw/data_base/unemployment-rates-24.csv")
df_work2 = pd.read_csv("../data/raw/data_base/unemployment-rates-23.csv")
df_work3 = pd.read_csv("../data/raw/data_base/unemployment-rates-22.csv")
df_work4 = pd.read_csv("../data/raw/data_base/unemployment-rates-21.csv")
df_work5 = pd.read_csv("../data/raw/data_base/unemployment-rates-19.csv")
df_work6 = pd.read_csv("../data/raw/data_base/unemployment-rates-18.csv")

df_work1.head()

In [2]:
df_work24 = df_work1[["NAME","S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2024"})
df_work23 = df_work2[["NAME", "S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2023"})
df_work22 = (df_work3[["NAME", "S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2022"}))
df_work21 = (df_work4[["NAME", "S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2021"}))
df_work19 = (df_work5[["NAME", "S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2019"}))
df_work18 = (df_work6[["NAME", "S2301_C04_001E"]].iloc[1:].rename(columns={"S2301_C04_001E": "2018"}))

df_work19.head()

                       NAME 2019
1      Auburn city, Alabama  3.6
2  Birmingham city, Alabama  7.3
3      Dothan city, Alabama  6.9
4      Hoover city, Alabama  3.7
5  Huntsville city, Alabama  4.0

In [3]:
df_work = (
    df_work24
    .merge(df_work23, on="NAME", how="left")
    .merge(df_work22, on="NAME", how="left")
    .merge(df_work21, on="NAME", how="left")
    .merge(df_work19, on="NAME", how="left")
    .merge(df_work18, on="NAME", how="left")
)

df_work.head()

                       NAME 2024 2023 2022 2021 2019  2018
0      Auburn city, Alabama    N  5.7  3.2    N  3.6     N
1  Birmingham city, Alabama  4.6  3.5  6.3  7.4  7.3  10.0
2      Dothan city, Alabama  5.5  3.4  4.9  5.3  6.9   6.0
3      Hoover city, Alabama    N  1.9    N  3.5  3.7   2.4
4  Huntsville city, Alabama  3.3  3.5  4.3  3.9  4.0   5.5

In [4]:
df_work_clean = df_work.melt(
    id_vars="NAME",                               
    value_vars=["2018", "2019",
                "2021", "2022",
                "2023", "2024"],    
    var_name="year",                              
    value_name="unemployment rate" 
)
df_work_clean.head()

                       NAME  year unemployment rate
0      Auburn city, Alabama  2018                 N
1  Birmingham city, Alabama  2018              10.0
2      Dothan city, Alabama  2018               6.0
3      Hoover city, Alabama  2018               2.4
4  Huntsville city, Alabama  2018               5.5

In [5]:
df_work_clean = df_work_clean.rename(columns={"NAME": "city"})
df_work_clean.head()

                       city  year unemployment rate
0      Auburn city, Alabama  2018                 N
1  Birmingham city, Alabama  2018              10.0
2      Dothan city, Alabama  2018               6.0
3      Hoover city, Alabama  2018               2.4
4  Huntsville city, Alabama  2018               5.5

In [6]:
df_work_states = df_work_clean.copy()
df_work_states[["city","state"]] = df_work_states["city"].str.rsplit(", ", n=1, expand=True)
df_work_states.head()

              city  year unemployment rate    state
0      Auburn city  2018                 N  Alabama
1  Birmingham city  2018              10.0  Alabama
2      Dothan city  2018               6.0  Alabama
3      Hoover city  2018               2.4  Alabama
4  Huntsville city  2018               5.5  Alabama

In [7]:
df_work_states.shape

(3942, 4)

### Median Household Income 2021-2024

In [ ]:
# Median Household Income

df_y1 = pd.read_csv("../data/raw/data_base/median_income2023.csv")
df_y2 = pd.read_csv("../data/raw/data_base/median_income2024.csv")
df_y3 = pd.read_csv("../data/raw/data_base/median_income2021.csv")
df_y4 = pd.read_csv("../data/raw/data_base/median_income2022.csv")
df_y5 = pd.read_csv("../data/raw/data_base/median_income2018.csv")
df_y6 = pd.read_csv("../data/raw/data_base/median_income2019.csv")

df_y6.head()

In [10]:
df_y1_clean = df_y1[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2023"})
df_y2_clean = df_y2[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2024"})
df_y3_clean = df_y3[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2021"})
df_y4_clean = df_y4[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2022"})
df_y5_clean = df_y5[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2018"})
df_y6_clean = df_y6[["NAME", "B19013_001E"]].iloc[1:].rename(columns={"B19013_001E": "income_2019"})

df_y6_clean.head()

                       NAME income_2019
1      Auburn city, Alabama       46031
2  Birmingham city, Alabama       36753
3      Dothan city, Alabama       47411
4      Hoover city, Alabama       98689
5  Huntsville city, Alabama       54342

In [11]:
income_merged = (
    df_y1_clean
    .merge(df_y2_clean, on="NAME")
    .merge(df_y3_clean, on="NAME")
    .merge(df_y4_clean, on="NAME")
    .merge(df_y5_clean, on="NAME")
    .merge(df_y6_clean, on="NAME")
)

income_merged.head()

,NAME,income_2023,income_2024,income_2021,income_2022,income_2018,income_2019
0,"Auburn city, Alabama",52259,69615,48531,54839,46436,46031
1,"Birmingham city, Alabama",44951,51355,36614,39326,36395,36753
2,"Dothan city, Alabama",54598,55846,45088,53929,49160,47411
3,"Hoover city, Alabama",102009,106844,99276,103194,87355,98689
4,"Huntsville city, Alabama",73319,83235,70757,68930,55405,54342

In [13]:
income_merged = income_merged.rename(columns={"NAME": "city"})
income_merged = income_merged[
    ["city", "income_2018", "income_2019",
     "income_2021", "income_2022", "income_2023", "income_2024"]
]
income_merged.head()

,city,income_2018,income_2019,income_2021,income_2022,income_2023,income_2024
0,"Auburn city, Alabama",46436,46031,48531,54839,52259,69615
1,"Birmingham city, Alabama",36395,36753,36614,39326,44951,51355
2,"Dothan city, Alabama",49160,47411,45088,53929,54598,55846
3,"Hoover city, Alabama",87355,98689,99276,103194,102009,106844
4,"Huntsville city, Alabama",55405,54342,70757,68930,73319,83235

In [15]:
# change the table to only three column
income_clean = income_merged.melt(
    id_vars="city",
    value_vars=["income_2018", "income_2019",
                "income_2021", "income_2022",
                "income_2023", "income_2024"],
    var_name="year",
    value_name="income"
)

income_clean.head()

                       city         year income
0      Auburn city, Alabama  income_2018  46436
1  Birmingham city, Alabama  income_2018  36395
2      Dothan city, Alabama  income_2018  49160
3      Hoover city, Alabama  income_2018  87355
4  Huntsville city, Alabama  income_2018  55405

In [16]:
income_clean["year"] = income_clean["year"].str[-4:].astype(int)
income_clean.head()

                       city  year income
0      Auburn city, Alabama  2018  46436
1  Birmingham city, Alabama  2018  36395
2      Dothan city, Alabama  2018  49160
3      Hoover city, Alabama  2018  87355
4  Huntsville city, Alabama  2018  55405

In [17]:
# add state columns
income_clean[["city", "state"]] = income_clean["city"].str.rsplit(", ", n=1, expand=True)
income_clean.head(10)

                     city  year income    state
0             Auburn city  2018  46436  Alabama
1         Birmingham city  2018  36395  Alabama
2             Dothan city  2018  49160  Alabama
3             Hoover city  2018  87355  Alabama
4         Huntsville city  2018  55405  Alabama
5             Mobile city  2018  38643  Alabama
6         Montgomery city  2018  49070  Alabama
7         Tuscaloosa city  2018  43468  Alabama
8  Anchorage municipality  2018  83648   Alaska
9           Avondale city  2018  63242  Arizona

In [18]:
income_clean.shape

(3672, 4)

In [20]:
df_work_states.shape

(3942, 4)

In [24]:
# Merge the two datasets

income_clean["year"] = income_clean["year"].astype(int)
df_work_states["year"] = df_work_states["year"].astype(int)

merged_panel = income_clean.merge(
    df_work_states,
    on=["city", "year", "state"],   # ensure exact match
    how="inner"
)

merged_panel.head()

              city  year income    state unemployment rate
0      Auburn city  2018  46436  Alabama                 N
1  Birmingham city  2018  36395  Alabama              10.0
2      Dothan city  2018  49160  Alabama               6.0
3      Hoover city  2018  87355  Alabama               2.4
4  Huntsville city  2018  55405  Alabama               5.5

In [26]:
merged_panel.shape

(3672, 5)

In [ ]:
df_age_sex_edu = pd.read_csv("../data/raw/data_base/age_sex_edu_df.csv")
df_age_sex_edu.head()

In [28]:
merged_final = df_age_sex_edu.merge(
    merged_panel,
    on=["city", "year", "state"],   # ensure exact match
    how="inner"
)

merged_final.head()

,city,state,year,median_age,sex_ratio,average_years_schooling,income,unemployment rate
0,Phoenix city,Arizona,2018,33.5,98.7,13.20,57957,4.8
1,Tucson city,Arizona,2018,33.5,96.7,13.37,43676,5.7
2,Los Angeles city,California,2018,35.8,100.0,12.95,62474,6.0
3,Sacramento city,California,2018,34.3,94.8,13.46,65046,6.5
4,San Diego city,California,2018,35.4,102.0,14.22,79646,5.3

In [29]:
merged_final.shape

(306, 8)

In [ ]:
merged_panel.to_csv("../data/cleaned/independent_variables.csv", index=False)